baseurl = "https://joaoarthurbm.github.io/eda"
title = "Estrutura de Dados"
copyright = "Copyright &copy; 2019 - João Arthur Brunet"
canonifyurls = true
theme = "kiera"
themesDir = "themes"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "João Arthur Brunet"
    github = "http://joaoarthurbm.github.io"
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = "joaobrunet"
    instagram = "joaoarthurbm"

[params]
    tagline = "João Arthur Brunet - Computação @ UFCG"
